name: backend-ci-cd
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        run: python -m pytest -v

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM
        run: >
          az deployment group create
          --resource-group rg-cloud-resume
          --template-file backend/infrastructure/azuredeploy.json
          --parameters backend/infrastructure/azuredeploy.parameters.json

      - name: Set app settings
        run: >
          az functionapp config appsettings set
          --name fa-calebresume-dev-linux
          --resource-group rg-cloud-resume
          --settings
          COSMOS_TABLE_CONN_STR='${{ secrets.COSMOS_TABLE_CONN_STR }}'
          COSMOS_TABLE_NAME='VisitorCounter'
          COSMOS_PARTITION_KEY='counter'
          COSMOS_ROW_KEY='global'

      - name: Publish Function
        uses: Azure/functions-action@v1
        with:
          app-name: fa-calebresume-dev-linux
          package: backend
          scm-do-build-during-deployment: true