name: backend-ci-cd

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

env:
  AZURE_FUNCTIONAPP_NAME: fa-calebresume-dev-linux
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      # Checkout the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      # Setup Python environment
      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install Python dependencies
      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      # Run tests (optional but recommended)
      - name: 'Run Python Tests'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pytest -v || echo "No tests found or tests failed"
          popd

      # Azure Login using OIDC
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Verify Azure connection
      - name: 'Verify Azure Connection'
        run: |
          az account show
          az group list --query "[].name" -o table

      # Deploy ARM Template (Infrastructure)
      - name: 'Deploy Azure Infrastructure'
        run: |
          az deployment group create \
            --resource-group rg-cloud-resume \
            --template-file ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/infrastructure/azuredeploy.json \
            --parameters ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/infrastructure/azuredeploy.parameters.json \
            --verbose

      # Configure Function App Settings
      - name: 'Configure Function App Settings'
        run: |
          az functionapp config ap
