name: backend-ci-cd

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: fa-calebresume-dev-linux
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: bash
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Run tests
        shell: bash
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          python -m pytest -v || echo "No tests found or tests failed"
          popd

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Select subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure connection
        run: |
          az account show
          az group list --query "[].name" -o table

      - name: Deploy infrastructure
        run: |
          az deployment group create \
            --resource-group rg-cloud-resume \
            --template-file ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/infrastructure/azuredeploy.json \
            --parameters @${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/infrastructure/deploymentParameters.json \
            --verbose

      - name: Configure Function App settings
        shell: bash
        run: |
          set -x
          az functionapp config appsettings set \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --resource-group rg-cloud-resume \
            --settings \
              COSMOS_TABLE_CONN_STR="${{ secrets.COSMOS_TABLE_CONN_STR }}" \
              COSMOS_TABLE_NAME="${{ secrets.COSMOS_TABLE_NAME }}" \
              COSMOS_PARTITION_KEY="${{ secrets.COSMOS_PARTITION_KEY }}" \
              COSMOS_ROW_KEY="${{ secrets.COSMOS_ROW_KEY }}" \
              EMAILJS_PUBLIC_KEY="${{ secrets.EMAILJS_PUBLIC_KEY }}" \
              EMAILJS_SERVICE_ID="${{ secrets.EMAILJS_SERVICE_ID }}" \
              EMAILJS_TEMPLATE_ID="${{ secrets.EMAILJS_TEMPLATE_ID }}" \
              FUNCTIONS_WORKER_RUNTIME=python \
            --verbose

      - name: Deploy Function App code
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true

      - name: Post-deployment check
        run: |
          echo "Deployment complete"
          az functionapp show \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --resource-group rg-cloud-resume \
            --query state -o tsv
